### ISSUE TITLE
Pack the interface into the module

### ISSUE THREAD

**Issue by XVilka** [madroach/ocaml-zlib#5]
Or maybe even split inflate/deflate into two separate modules.

**Comment by madroach** [comment]
I'm afraid I do not understand your request. Could you please elaborate?

**Comment by XVilka** [comment]
Provide modules like `Inflate` and `Deflate`, or something like that. It is just a suggestion.

**Comment by madroach** [comment]
So you suggest moving the ``inflate_…`` functions to module ``Inflate`` and the ``deflate_…`` functions to module ``Deflate``, along with the two pseudotypes ``inflate`` and ``deflate``.
Yes, this might be a easier to understand structure. But it would be a breaking change and not much to gain by it. Since the types are just pseudotypes can't see any technical reasons for separating them.

**Comment by madroach** [comment]
Feel free to reopen if you really think this would be a relevant improvement.
